script:
  - |
    git config user.name "MajsoulPlus-WikiBot"
    git config user.email "mail@bysb.net"
    git remote remove origin
    git remote add origin https://$GITHUB_TOKEN@github.com/MajsoulPlus/majsoul-plus-wiki.git > /dev/null 2>&1
    git remote add upstream https://$GITHUB_TOKEN@github.com/MajsoulPlus/majsoul-plus.wiki.git > /dev/null 2>&1
    git fetch origin
    git fetch upstream
    git merge upstream/master --no-edit
    git push origin HEAD:master > /dev/null 2>&1
    git push upstream HEAD:master > /dev/null 2>&1
